### ISSUE TITLE
Cool Project!

### ISSUE THREAD

**Issue by ABGEO** [crissyfield/repo-lookout#10]
Hello there,

I must say, your project is really impressive! I was wondering if there is an opportunity for me to contribute to the source code. I would be thrilled to get involved.

**Comment by tja** [comment]
Hi there.

Thanks for the kind words and your interest in contributing, it's much appreciated. Unfortunately, the source code is not yet publicly available. We are working on getting legal approval and cleaning things up, but it will take a while. As soon as we are ready, we'll let you know!

Cheers, --Thomas

**Comment by HolgerJeromin** [comment]
I just want to thank you, too!

Got an email just now and added the config within minutes.

**Comment by tja** [comment]
Hi @HolgerJeromin .

Thank you very much for the kind words — it's always great to hear when people see value in the project! And thank you for taking the email seriously and fixing the issue!

Cheers, --Thomas
