### ISSUE TITLE
Wiki Apache Suggestion: RedirectMatch 404 /\.git

### ISSUE THREAD

**Issue by mgiambrone** [crissyfield/repo-lookout#14]
Suggesting to also use the following line with in the Apache section of the wiki:
RedirectMatch 404 /\.git
This way it doesn't even show that git is being used. I would suggest keeping the directory match as well to prevent .git from being listed in the open directory if the directory is exposed.

**Comment by tja** [comment]
Thank you for the suggestion!

I have extended the Wiki articles for Apache, nginx, and Caddy to cover returning `404`s instead of `403`s.
