### ISSUE TITLE
Wiki: Apache - Add description for .htaccess usage

### ISSUE THREAD

**Issue by ebroda** [crissyfield/repo-lookout#17]
I'm running my services on a shared hosting where I don't have access to the httpd.conf. Therefore the configuration hints, shown on https://github.com/crissyfield/repo-lookout/wiki/Apache, don't help me.

It might be good, to also add also the way using the .htaccess. Maybe also including a hint, that the other way is prefered but this a possible fallback.

This could be e.g.
```
RewriteEngine On
RewriteRule ^\.git - [F]
```

**Comment by tja** [comment]
Thank you for bringing this up! I'll have a look.

**Comment by tja** [comment]
This has been fixed.
