### ISSUE TITLE
add Apache 2.4 to "Git repository exposure in Apache" WIki page

### ISSUE THREAD

**Issue by camslice** [crissyfield/repo-lookout#18]
Currently [this Wiki page](https://github.com/crissyfield/repo-lookout/wiki/Apache) shows syntax for Apache 2.2:

```
<DirectoryMatch "/\.git">
    Deny from all
</DirectoryMatch>
```

Syntax for Apache 2.4 should be added 

```
<DirectoryMatch "/\.git">
    Require all denied
</DirectoryMatch>
```

**Comment by tja** [comment]
Thank you so much for pointing this out. This has been fixed.

**Comment by camslice** [comment]
my pleasure, thanks for providing such a valuable service.  made a donation yesterday.  keep it up!
